/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LanguageTag = IDL.Text;
export const Emotion = IDL.Variant({
  'sad' : IDL.Null,
  'happy' : IDL.Null,
  'angry' : IDL.Null,
  'excited' : IDL.Null,
  'neutral' : IDL.Null,
});
export const TranslationRecord = IDL.Record({
  'sourceLanguage' : LanguageTag,
  'detectedEmotion' : Emotion,
  'originalText' : IDL.Text,
  'targetLanguage' : LanguageTag,
  'translatedText' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'getTranslationHistory' : IDL.Func(
      [],
      [IDL.Vec(TranslationRecord)],
      ['query'],
    ),
  'saveTranslation' : IDL.Func(
      [IDL.Text, IDL.Text, LanguageTag, LanguageTag, Emotion],
      [],
      [],
    ),
  'translateAndSave' : IDL.Func(
      [IDL.Text, LanguageTag, LanguageTag],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LanguageTag = IDL.Text;
  const Emotion = IDL.Variant({
    'sad' : IDL.Null,
    'happy' : IDL.Null,
    'angry' : IDL.Null,
    'excited' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const TranslationRecord = IDL.Record({
    'sourceLanguage' : LanguageTag,
    'detectedEmotion' : Emotion,
    'originalText' : IDL.Text,
    'targetLanguage' : LanguageTag,
    'translatedText' : IDL.Text,
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'getTranslationHistory' : IDL.Func(
        [],
        [IDL.Vec(TranslationRecord)],
        ['query'],
      ),
    'saveTranslation' : IDL.Func(
        [IDL.Text, IDL.Text, LanguageTag, LanguageTag, Emotion],
        [],
        [],
      ),
    'translateAndSave' : IDL.Func(
        [IDL.Text, LanguageTag, LanguageTag],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };