/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TranslationRecord {
    sourceLanguage: LanguageTag;
    detectedEmotion: Emotion;
    originalText: string;
    targetLanguage: LanguageTag;
    translatedText: string;
}
export type LanguageTag = string;
export enum Emotion {
    sad = "sad",
    happy = "happy",
    angry = "angry",
    excited = "excited",
    neutral = "neutral"
}
export interface backendInterface {
    clearHistory(): Promise<void>;
    getTranslationHistory(): Promise<Array<TranslationRecord>>;
    saveTranslation(originalText: string, translatedText: string, sourceLanguage: LanguageTag, targetLanguage: LanguageTag, detectedEmotion: Emotion): Promise<void>;
    translateAndSave(text: string, sourceLang: LanguageTag, targetLang: LanguageTag): Promise<string>;
}
import type { Emotion as _Emotion, LanguageTag as _LanguageTag, TranslationRecord as _TranslationRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearHistory();
            return result;
        }
    }
    async getTranslationHistory(): Promise<Array<TranslationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTranslationHistory();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTranslationHistory();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveTranslation(arg0: string, arg1: string, arg2: LanguageTag, arg3: LanguageTag, arg4: Emotion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTranslation(arg0, arg1, arg2, arg3, to_candid_Emotion_n6(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTranslation(arg0, arg1, arg2, arg3, to_candid_Emotion_n6(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async translateAndSave(arg0: string, arg1: LanguageTag, arg2: LanguageTag): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.translateAndSave(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.translateAndSave(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Emotion_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Emotion): Emotion {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TranslationRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TranslationRecord): TranslationRecord {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sourceLanguage: _LanguageTag;
    detectedEmotion: _Emotion;
    originalText: string;
    targetLanguage: _LanguageTag;
    translatedText: string;
}): {
    sourceLanguage: LanguageTag;
    detectedEmotion: Emotion;
    originalText: string;
    targetLanguage: LanguageTag;
    translatedText: string;
} {
    return {
        sourceLanguage: value.sourceLanguage,
        detectedEmotion: from_candid_Emotion_n4(_uploadFile, _downloadFile, value.detectedEmotion),
        originalText: value.originalText,
        targetLanguage: value.targetLanguage,
        translatedText: value.translatedText
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    excited: null;
} | {
    neutral: null;
}): Emotion {
    return "sad" in value ? Emotion.sad : "happy" in value ? Emotion.happy : "angry" in value ? Emotion.angry : "excited" in value ? Emotion.excited : "neutral" in value ? Emotion.neutral : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TranslationRecord>): Array<TranslationRecord> {
    return value.map((x)=>from_candid_TranslationRecord_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Emotion_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Emotion): _Emotion {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Emotion): {
    sad: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    excited: null;
} | {
    neutral: null;
} {
    return value == Emotion.sad ? {
        sad: null
    } : value == Emotion.happy ? {
        happy: null
    } : value == Emotion.angry ? {
        angry: null
    } : value == Emotion.excited ? {
        excited: null
    } : value == Emotion.neutral ? {
        neutral: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
